version: '3.8'

services:
  # Frontend React application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: minecraft-mod-client
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - minecraft-mod-network

  # Backend Node.js API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: minecraft-mod-server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/minecraft_mod_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=7d
      - SERVERS_PATH=/app/data/servers
    volumes:
      - server_data:/app/data
    networks:
      - minecraft-mod-network

  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: minecraft-mod-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=minecraft_mod_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minecraft-mod-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: minecraft-mod-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - minecraft-mod-network

  # Minecraft server manager (uses Docker in Docker)
  server-manager:
    build:
      context: ./server-manager
      dockerfile: Dockerfile
    container_name: minecraft-server-manager
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - minecraft_servers:/minecraft
    depends_on:
      - server
    networks:
      - minecraft-mod-network

volumes:
  postgres_data:
  redis_data:
  server_data:
  minecraft_servers:

networks:
  minecraft-mod-network:
    driver: bridge